config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root to: 'pages#home'

  get '/help', to: 'pages#help'

  resources :cities, only: [:create, :destroy, :show] do
    collection do
      get 'refresh'
    end
  end

  namespace :api, defaults: { format: :json } do
    namespace :v1 do
      resources :cities, only: [ :index ]
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/city.rb
require 'net/http'
require 'json'
require 'faker'

class City < ApplicationRecord
  belongs_to :user

  before_save :downcase_name
  validate :city_exist?
  # before_create :add_timezone
  validates :name, presence: true, uniqueness: { case_sensitive: false }, length: { maximum: 40 }

  class << self
    def get_weather(name, type = 'forecast')
      api_key = '9a7b845155f83f747b6d779db8d8e652'

      uri = URI("http://api.openweathermap.org/data/2.5/#{type}?q=#{CGI.escape(name)}&units=metric&appid=#{api_key}")

      res = JSON.parse(Net::HTTP.get(uri))
    end

    # Revtrieves the photo url from api
    def get_city_picture(name)
      name = name.strip.gsub!(/\s/, '-') if name =~ /\s/
      uri = URI("https://api.teleport.org/api/urban_areas/slug:#{CGI.escape(name)}/images/")

      pho = JSON.parse(Net::HTTP.get(uri))

      if pho['status'] == 404
        pho = "https://www.touropia.com/gfx/d/small-towns-in-brazil/iguape.jpg?v=98b61a48722deeff9138c5d25a96bc12"
      else
        pho = pho["photos"][0]["image"]["web"]
      end
    end
  end

private

  # Converts city name to all lower-case.
  def downcase_name
    name.downcase!
  end

  # Checks if inserted city exists
  def city_exist?
    return false if self.payload.nil?
    if (self.payload['cod'] == '404')
      self.errors[:base] << 'city does not exist'
    else
      true
    end
  end

  # Lookup the correct timezone based on the latitude and longitude. (https://github.com/panthomakos/timezone) -not working, still need to finish
  def add_timezone
    res = City.get_weather(name)

    begin
      self.timezone = Timezone.lookup(res['city']['coord']['lat'], res['city']['coord']['lon']).name
    rescue Timezone::Error::Base => e
      puts "Timezone Error: #{e.message}"
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :cities
end

app/controllers/api/v1/base_controller.rb
class Api::V1::BaseController < ActionController::API
  include Pundit

  after_action :verify_authorized, except: :index
  after_action :verify_policy_scoped, only: :index

  rescue_from StandardError,                with: :internal_server_error
  rescue_from Pundit::NotAuthorizedError,   with: :user_not_authorized
  rescue_from ActiveRecord::RecordNotFound, with: :not_found

  private

  def user_not_authorized(exception)
    render json: {
      error: "Unauthorized #{exception.policy.class.to_s.underscore.camelize}.#{exception.query}"
    }, status: :unauthorized
  end

  def not_found(exception)
    render json: { error: exception.message }, status: :not_found
  end

  def internal_server_error(exception)
    if Rails.env.development?
      response = { type: exception.class.to_s, message: exception.message, backtrace: exception.backtrace }
    else
      response = { error: "Internal Server Error" }
    end
    render json: response, status: :internal_server_error
  end
end

app/controllers/api/v1/cities_controller.rb
class Api::V1::CitiesController < Api::V1::BaseController
  def index
    @cities = policy_scope(City)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!

  include Pundit

  # Pundit: white-list approach.
  after_action :verify_authorized, except: :index, unless: :skip_pundit?
  after_action :verify_policy_scoped, only: :index, unless: :skip_pundit?

  # Uncomment when you *really understand* Pundit!
  # rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized
  # def user_not_authorized
  #   flash[:alert] = "You are not authorized to perform this action."
  #   redirect_to(root_path)
  # end

  private

  def skip_pundit?
    devise_controller? || params[:controller] =~ /(^(rails_)?admin)|(^pages$)/
  end
end

app/controllers/cities_controller.rb
class CitiesController < ApplicationController
  def show
    @city = City.find(params[:id])
    authorize @city
  end

  def create
    @city = City.new(name: params[:location][:city_name].downcase)
    @city.user = current_user
    @city.payload = City.get_weather(@city.name)
    @city.photo = City.get_city_picture(@city.name)
    authorize @city
    if @city.save
      redirect_to root_path, flash: { notice: 'City added' }
    else
      redirect_to root_path, flash: { alert: 'City does not exist or already in the list' }
    end
  end

  def refresh
    @cities = City.all
    authorize @cities

    @cities.each do |city|
      city.update(payload: City.get_weather(city.name))
    end

    redirect_to root_path
  end

  def destroy
    @city = City.find(params[:id])
    authorize @city
    @city.destroy

    redirect_to root_path

    # AJAX to be finished

    #   respond_to do |format|
    #   if @result = @city.destroy
    #     format.html { redirect_to root_url }
    #     format.js
    #   else
    #     format.html {
    #       @city.errors.full_messages.each do |msg|
    #         flash[:danger] = msg
    #       end
    #       redirect_to root_url
    #     }
    #     format.js
    #   end
    # end
  end

  def api; end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!

  def home
    @cities = City.all.order(created_at: :desc)
  end

  def help
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/cities/show.html.erb
<h1 class="text-center"> <%= @city.name.capitalize %></h1>

<div class="cards">
  <% @city.payload['list'].each do |forecast| %>
    <div class="card-category">
      <h4 class="card-title"><%= Date.parse(forecast['dt_txt']).strftime("%a") %></h4>
      <h6 class="card-subtitle text-muted"><%= Date.parse(forecast['dt_txt']).strftime("%x") %></br><%= forecast['dt_txt'].split(" ")[1][0..4] %></h6>
      <img src="https://openweathermap.org/img/w/<%= forecast['weather'][0]['icon']%>.png">
      <div class="temperature">
        <h1><%= forecast['main']['temp'].to_i %>°</h1>
      </div>
    </div>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Weather Forecast Challenge</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%#= stylesheet_pack_tag 'application', media: 'all' %> <!-- Uncomment if you import CSS in app/javascript/packs/application.js -->
  </head>
  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>
    <%= yield %>
    <%= render 'shared/footbar' %>
    <%= javascript_include_tag 'application' %>
    <%= javascript_pack_tag 'application' %>
  </body>
</html>

app/views/pages/help.html.erb
<% provide(:title, "Help") %>
<h1 class="text-center">Help</h1>
<p class="help-paragraph">
  This application displays the weather forecast. Sign in to discover its functionality.
  </br>
  </br>
  On the home page you are able to see the current weather - make sure you refresh data to get the fresh weather by the button in navbar.
  There are 3 default fixed cities on display: Tallinn, Tartu and Brno, but additionaly you are able to add or delete your own cities through search form in navbar. Only you are able to delete cities which you created.
  </br>
  </br>
  In the show page, after clicking on Forecast 5/3, you can see detailed 5 day per 3 hour forecast for speficic city, on the cards. (more visual chart is currently under construction).
  </br>
  </br>
  After signin in you are also able to redirect to API of the page by clicking on the avatar and choosing API.
</p>

app/views/pages/home.html.erb
<div class="body-wrap">
  <% if @cities.blank? == false  %>
    <% @cities.each do |city|  %>
        <div class="card-product">
          <img class="card-photo img-thumbnail" src=" <%= city.photo %>">
          <div class="card-product-infos">
            <h2><%= city.name.capitalize %></h2>
          </div>
          <div class="card-product-details">
            <div class="card-product-weather">
              <img src="https://openweathermap.org/img/w/<%= city.payload['list'][0]['weather'][0]['icon']%>.png">
              <div class="card-product-weather-detail">
                <h2> <%= city.payload['list'][0]['main']['temp'].to_i %>°C</h2><h6 class="card-product-subtitle"><%= city.payload['list'][0]['weather'][0]['description'] %></h6>
              </div>
            </div>
            <div class="card-product-footer">
              <%= link_to "Forecast", city_path(city)%>
                <% if policy(city).destroy? %>
                  <%= link_to 'Delete', city_path(city), method: :delete,
              data: {confirm: "Are you sure you want to delete card for #{city.name.capitalize}?"}, lass: "btn btn-danger"%>
              <% end %>
<!--               <%= link_to '<span>&times;<span>'.html_safe, @city, remote: true, method: :delete %> -->
            </div>
          </div>
        </div>
    <% end %>
  <% end %>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_footbar.html.erb
<div class="footer">
  <div class="footer-links">
    <p>Thank you for using <small>© Weather App</small></p>
  </div>
  <div class="footer-links">
    <a href="#">About</a>
    <a href="#">Contact</a>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <%= link_to root_path, class: "navbar-brand" do %>
  <h3>Weather app</h3>
    <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
    <% if !@cities.nil? %>
      <% if policy(City).create? %>
        <div class="search-form">
          <%= form_for :location, url: cities_path, method: :post do |f| %>
            <%= f.text_field :city_name %>
            <%= f.submit class:"btn btn-dark" %>
          <% end  %>
        </div>
      <% end %>
    <% end %>

    <% if !@cities.nil? %>
        <div class="search-form">
          <%= button_to "Refresh data", refresh_cities_path, method: :get, class:"btn btn-light" %>
        </div>
    <% end %>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <%= link_to "Help", help_path, class: "nav-link" %>
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <%= link_to "Home", root_path, class: "nav-link home-link" %>
        <li class="nav-item dropdown">
          <%= image_tag "http://1.gravatar.com/avatar/ad516503a11cd5ca435acc9bb6523536?s=500", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "API", api_v1_cities_path, method: :get, class: "dropdown-item" %>
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>